logging.level.io.github.resilience4j: DEBUG
logging.level.io.eventuate.examples: INFO

apigateway.timeout.millis: 1000

customer:
  destinations:
    customerServiceUrl: http://localhost:9090
order:
  destinations:
    orderServiceUrl: http://localhost:9090

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 1
      waitDurationInOpenState: 10000
      failureRateThreshold: 60

spring:
  cloud:
    gateway:
      routes:
        - id: create_customer
          uri: ${customer.destinations.customerServiceUrl}
          predicates:
            - Method=POST
            - Path=/customers
          filters:
            - CircuitBreaker=myCircuitBreaker
        - id: create_order
          uri: ${order.destinations.orderServiceUrl}
          predicates:
            - Method=POST
            - Path=/orders
          filters:
            - CircuitBreaker=myCircuitBreaker
        - id: get_order
          uri: ${order.destinations.orderServiceUrl}
          predicates:
            - Method=get
            - Path=/orders/{orderId}
          filters:
            - CircuitBreaker=myCircuitBreaker

